{{ tpl (readFile "../common/repositories.yaml") . | nindent 0 }}

{{ tpl (readFile "../common/helm-defaults.yaml") . | nindent 0 }}

environments:
  staging:

{{ tpl (readFile "../common/templates.yaml") . | nindent 0 }}


- name: staging-goerli-0
  namespace: staging-goerli-0
  <<: *geth-goerli

- name: staging-goerli-1
  namespace: staging-goerli-1
  <<: *geth-goerli

- name: staging-prysm-0
  namespace: staging-prysm-0
  <<: *prysm

- name: staging-prysm-1
  namespace: staging-prysm-1
  <<: *prysm

- name: staging-nitro-0
  namespace: staging-nitro-0
  <<: *nitro

- name: staging-nitro-1
  namespace: staging-nitro-1
  <<: *nitro

