templates:

  # Geth execution client for L1 EVM
  _geth: &_geth
    chart: blockchain-k8s/geth
    version: {{ env "version" | default "" }}
    labels:
      client: execution
      chart: geth
    missingFileHandler: Debug
    kubeContext: {{ env "KUBE_CONTEXT" | default ( printf "baas-gke-%s-baas0" .Environment.Name ) }}

  # Goerli L1 testnet EVM execution client
  geth-goerli: &geth-goerli
    <<: *_geth
    labels:
      chain: 5
    values:
      - ../common/values-geth.yaml
      - ../common/values-geth-goerli.yaml
      - values-{{`{{ .Release.Name }}`}}.yaml
      - values-{{`{{ .Release.Name }}`}}-custom.yaml

  # Prysm consensus client for L1 EVM
  _prysm: &_prysm
    chart: blockchain-k8s/prysm
    version: {{ env "version" | default "" }}
    labels:
      client: consensus
      chart: prysm
    missingFileHandler: Debug
    kubeContext: {{ env "KUBE_CONTEXT" | default ( printf "baas-gke-%s-baas0" .Environment.Name ) }}

  # Praeter L1 testnet EVM consensus client
  prysm-praeter: &prysm-praeter
    <<: *_prysm
    labels:
      chain: 5
    values:
      - ../common/values-prysm.yaml
      - ../common/values-prysm-praeter.yaml
      - values-{{`{{ .Release.Name }}`}}.yaml
      - values-{{`{{ .Release.Name }}`}}-custom.yaml
    
  # Avalanche Nitro L2 client
  _nitro: &_nitro
    chart: blockchain-k8s/nitro
    version: {{ env "version" | default "" }}
    labels:
      client: l2
      chart: nitro
    missingFileHandler: Debug
    kubeContext: {{ env "KUBE_CONTEXT" | default ( printf "baas-gke-%s-baas0" .Environment.Name ) }}

  # Arbitrum Nitro Goerli L2 testnet client
  nitro-goerli: &_nitro
    <<: *_nitro
    labels:
      chain: 42163
    values:
      - ../common/values-nitro.yaml
      - ../common/values-nitro-goerli.yaml
      - values-{{`{{ .Release.Name }}`}}.yaml
      - values-{{`{{ .Release.Name }}`}}-custom.yaml