geth:
  chain: 5
persistence:
  size: "500Gi"

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: "geth"
              geth/chain: "5"
          topologyKey: failure-domain.beta.kubernetes.io/zone
