configurationFile:
  rpcuser: "rpcuser"
  rpcpassword: "rpcpassword"

persistence:
  enabled: true
  storageClass: "standard-regional-us-central1-bc"
#  Disk size can not be smaller than 200 GB for regional disks
  size: "200Gi"

image:
  repository: blockchainetl/dashd
  tag: 0.14.0.3
  pullPolicy: IfNotPresent

nameOverride: "dashd"

bitcoind:
  base_path: /home/dash
  configurationFileName: "dash.conf"
  cli_binary: "dash-cli"
  chain: "dash"

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: "dashd"
          topologyKey: failure-domain.beta.kubernetes.io/zone

service:
  rpcPort: 9998
  p2pPort: 9999

resources:
  requests:
    cpu: "1000m"
    memory: "2000Mi"
  limits:
    cpu: "2000m"
    memory: "3000Mi"
