parity:
  chain: kovan
persistence:
  size: "500Gi"

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: "parity"
              parity/chain: "kovan"
          topologyKey: failure-domain.beta.kubernetes.io/zone
