{{- tpl (readFile "common/repositories.yaml") . | nindent 0 }}

{{- tpl (readFile "common/helm-defaults.yaml") . | nindent 0 }}
environments:
  staging:
  replaceme:
helmfiles:
  - staging/helmfile.yaml
  - replaceme/helmfile.yaml
