apiVersion: apps/v1
kind: Deployment
metadata:
  name: geth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geth
  template:
    metadata:
      labels:
        app: geth
    spec:
      containers:
      - name: geth
        image: ethereum/client-go:stable
        args:
        - --http
        - --http.addr=0.0.0.0
        - --http.vhosts="*"
        - --http.corsdomain="*"
        - --http.api=eth,net,web3
        ports:
        - containerPort: 8545
        volumeMounts:
        - name: geth-data
          mountPath: /root/.ethereum
      volumes:
      - name: geth-data
        persistentVolumeClaim:
          claimName: geth-data-claim